### ISSUE TITLE
Application crashes with "NotSupportedException" onces a day

### ISSUE THREAD

**Issue by k0st1x** [Xarlot/DXVcs2Git#21]
**MessageBox:**
Unhandled exception
....
Ooooops, some shit happens :(
See log for details.
........
OK_

**Logs:**
_...
[17:43:56] Repositories update started
[17:44:00] Repositories update completed
[23:00:47] Unhandled exception, _

**Real Exception:**
_System.NotSupportedException: WebClient does not support concurrent I/O operations.
   at System.Net.WebClient.ClearWebClientState()
   at System.Net.WebClient.OpenReadAsync(Uri address, Object userToken)
   at System.Net.WebClient.OpenReadAsync(Uri address)
   at DXVcs2Git.UI.AtomFeed.FeedWorker.<>c.<Initialize>b__23_0(Object o, EventArgs e)
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)_

**Comment by Xarlot** [comment]
fixed since 1.2.17
